const assert=require('assert');const {crearEntorno}=require('./helpers/entorno-apps-script.js');
const HOY='2026-07-26',SEDE='San Antonio',OTRA='Capri';
function nuevo(){const env=crearEntorno();env.fijarReloj('2026-07-26T17:00:00-05:00');env.ctx.configurarHojas();env.ctx.crearAdministradorInicial_('Diana','diana','contrasegura1','diana@example.com');const l=env.post({action:'login',usuario:'diana',password:'contrasegura1'});assert.ok(l.ok);return {env,token:l.token};}
function ok(env,b){const r=env.post(b);assert.ok(r.ok,JSON.stringify(r));return r;}function falla(env,b){const r=env.post(b);assert.strictEqual(r.ok,false,JSON.stringify(r));return r;}

// Apertura obligatoria y reintento idempotente.
(function(){const {env,token}=nuevo(),p=b=>Object.assign({token},b);assert.strictEqual(ok(env,p({action:'caja_estado',fecha:HOY,sede:SEDE})).abierta,false);falla(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Otro ingreso',valor:5000,motivo:'sin abrir'}}));falla(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:0,caja_fuerte_contada:0}}));const a=ok(env,p({action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:50000,caja_fuerte_inicial:0,observacion_apertura:'inicio'}}));assert.equal(a.item.base_inicial,50000);const re=ok(env,p({action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:99999,caja_fuerte_inicial:0}}));assert.ok(re.ya_abierta);assert.equal(re.item.base_inicial,50000);})();

// Movimientos cambian el esperado inmediatamente.
(function(){const {env,token}=nuevo(),p=b=>Object.assign({token},b);ok(env,p({action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:50000,caja_fuerte_inicial:0,observacion_apertura:'inicio'}}));falla(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Entrega administrador',valor:20000,motivo:'sin personas'}}));ok(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Entrega administrador',valor:20000,persona_entrega:'Juan',persona_recibe:'Diana',motivo:'Entrega'}}));ok(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Otro ingreso',valor:3000,motivo:'Ingreso'}}));const s=ok(env,p({action:'caja_estado',fecha:HOY,sede:SEDE}));assert.equal(s.efectivo_esperado,33000);assert.equal(s.movimientos_resumen.entregas_administrador,20000);assert.equal(ok(env,p({action:'caja_movimientos_listar',fecha:HOY,sede:SEDE})).data.length,2);})();

// Cierre: no puede existir retiro implícito; el dinero debe salir como movimiento antes de cerrar.
(function(){const {env,token}=nuevo(),p=b=>Object.assign({token},b);ok(env,p({action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:50000,caja_fuerte_inicial:0,observacion_apertura:'inicio'}}));ok(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Entrega administrador desde caja',valor:20000,persona_entrega:'Juan',persona_recibe:'Diana',motivo:'Entrega'}}));const mal=falla(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:30000,caja_fuerte_contada:0,base_siguiente:20000}}));assert.ok(String(mal.error).includes('registra primero la entrega'));const cierre=ok(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:30000,caja_fuerte_contada:0,base_siguiente:30000}}));assert.equal(cierre.diferencia,0);assert.equal(cierre.base_siguiente,30000);const estado=ok(env,p({action:'caja_estado',fecha:HOY,sede:SEDE}));assert.equal(estado.apertura.entrega_cierre,0);assert.equal(estado.apertura.base_siguiente,30000);assert.ok(ok(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:999999,caja_fuerte_contada:0}})).ya_cerrado);falla(env,p({action:'caja_movimiento_registrar',item:{fecha:HOY,sede:SEDE,tipo:'Otro ingreso',valor:1000,motivo:'tarde'}}));})();

// Diferencia física no bloquea, pero exige observación.
(function(){const {env,token}=nuevo(),p=b=>Object.assign({token},b);ok(env,p({action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:50000,caja_fuerte_inicial:0,observacion_apertura:'inicio'}}));falla(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:45000,caja_fuerte_contada:0,base_siguiente:45000}}));const c=ok(env,p({action:'caja_cerrar',item:{fecha:HOY,sede:SEDE,efectivo_contado:45000,caja_fuerte_contada:0,base_siguiente:45000,observacion:'faltan 5.000'}}));assert.equal(c.diferencia,-5000);})();

// Permisos de sede y cierre.
(function(){const {env}=nuevo();const cocina={id:'u',nombre:'Juan',rol:'Cocina',sede:SEDE};assert.ok(env.ctx.cajaAbrir_({fecha:HOY,sede:SEDE,base_inicial:0,caja_fuerte_inicial:0},cocina).ok);assert.strictEqual(env.ctx.cajaAbrir_({fecha:HOY,sede:OTRA,base_inicial:0,caja_fuerte_inicial:0},cocina).ok,false);assert.strictEqual(env.ctx.cajaCerrar_({fecha:HOY,sede:SEDE,efectivo_contado:0,caja_fuerte_contada:0,base_siguiente:0},cocina).ok,false);})();

console.log('caja-turno: OK');
