/**
 * CORRECCIÓN DE UN CIERRE YA HECHO (cajaCorregir_) — solo Administrador.
 * El cierre inicial ya respeta la regla nueva: base_siguiente = efectivo contado. La prueba de
 * corrección sigue pudiendo modificar la base posteriormente porque ese es precisamente el flujo
 * administrativo auditado para corregir historia, no una salida implícita del cajero al cerrar.
 */
const assert = require('assert');
const { crearEntorno } = require('./helpers/entorno-apps-script.js');

const HOY='2026-07-26', AYER='2026-07-25', SEDE='San Antonio';
function nuevoEntornoConAdmin(){const env=crearEntorno();env.ctx.configurarHojas();env.ctx.crearAdministradorInicial_('Diana','diana','contrasegura1','diana@example.com');const login=env.post({action:'login',usuario:'diana',password:'contrasegura1'});assert.ok(login.ok);return {env,token:login.token};}
function abrirYCerrar(env,token,fecha,contado){const p=c=>Object.assign({token},c);const abrir=env.post(p({action:'caja_abrir',item:{fecha,sede:SEDE,base_inicial:0,caja_fuerte_inicial:0,observacion_apertura:'fixture de corrección: se documenta cualquier diferencia frente al cierre anterior'}}));assert.ok(abrir.ok,'abrir debió funcionar: '+JSON.stringify(abrir));const cerrar=env.post(p({action:'caja_cerrar',item:{fecha,sede:SEDE,efectivo_contado:contado,caja_fuerte_contada:0,base_siguiente:contado,observacion:'diferencia esperada en esta prueba'}}));assert.ok(cerrar.ok,'cerrar debió funcionar: '+JSON.stringify(cerrar));return cerrar;}

(function(){const {env,token}=nuevoEntornoConAdmin();abrirYCerrar(env,token,HOY,100000);const r=env.ctx.cajaCorregir_({fecha:HOY,sede:SEDE,efectivo_contado:120000,caja_fuerte_contada:0,motivo_correccion:'probar'},{rol:'Encargado',nombre:'Giselle',sede:SEDE,id:'u2'});assert.strictEqual(r.ok,false);assert.match(r.error,/Solo un Administrador/);})();
(function(){const {env,token}=nuevoEntornoConAdmin();env.post({token,action:'caja_abrir',item:{fecha:HOY,sede:SEDE,base_inicial:0,caja_fuerte_inicial:0}});const r=env.post({token,action:'caja_corregir',item:{fecha:HOY,sede:SEDE,efectivo_contado:1000,caja_fuerte_contada:0,motivo_correccion:'x'}});assert.strictEqual(r.ok,false);assert.match(r.error,/no está cerrada/);})();
(function(){const {env,token}=nuevoEntornoConAdmin();abrirYCerrar(env,token,HOY,100000);const r=env.post({token,action:'caja_corregir',item:{fecha:HOY,sede:SEDE,efectivo_contado:120000,caja_fuerte_contada:0}});assert.strictEqual(r.ok,false);assert.match(r.error,/motivo/);})();
(function(){const {env,token}=nuevoEntornoConAdmin();const cierre=abrirYCerrar(env,token,HOY,100000);assert.strictEqual(cierre.diferencia,100000);const r=env.post({token,action:'caja_corregir',item:{fecha:HOY,sede:SEDE,efectivo_contado:95000,caja_fuerte_contada:0,base_siguiente:5000,observacion_cierre:'se había leído mal el billete de $5.000',motivo_correccion:'el cajero contó de más por error'}});assert.ok(r.ok,'la corrección debió funcionar: '+JSON.stringify(r));assert.strictEqual(r.efectivo_contado,95000);assert.strictEqual(r.diferencia,95000);assert.strictEqual(r.base_siguiente,5000);const historial=env.post({token,action:'caja_historial_listar',fecha_desde:HOY,fecha_hasta:HOY,sede:SEDE});const fila=historial.historial[0];assert.strictEqual(Number(fila.efectivo_contado),95000);assert.strictEqual(fila.observacion_cierre,'se había leído mal el billete de $5.000');const eventos=env.ctx.leerTabla_(env.evaluar('SHEET_NAMES.AUDITORIA'));const evento=eventos.find(e=>e.accion==='caja_corregir');assert.ok(evento);assert.strictEqual(evento.usuario_nombre,'Diana');assert.match(evento.motivo,/contó de más/);const anterior=JSON.parse(evento.valor_anterior);assert.strictEqual(Number(anterior.efectivo_contado),100000);})();
(function(){const {env,token}=nuevoEntornoConAdmin();abrirYCerrar(env,token,AYER,100000);abrirYCerrar(env,token,HOY,100000);const r=env.post({token,action:'caja_corregir',item:{fecha:AYER,sede:SEDE,efectivo_contado:90000,caja_fuerte_contada:0,motivo_correccion:'x'}});assert.strictEqual(r.ok,false);assert.match(r.error,/más reciente/);const r2=env.post({token,action:'caja_corregir',item:{fecha:HOY,sede:SEDE,efectivo_contado:90000,caja_fuerte_contada:0,motivo_correccion:'x'}});assert.ok(r2.ok,'el cierre más reciente sí debe poder corregirse: '+JSON.stringify(r2));})();
(function(){const {env,token:tokenAdmin}=nuevoEntornoConAdmin();abrirYCerrar(env,tokenAdmin,HOY,100000);const nuevoUsuario=env.post({token:tokenAdmin,action:'usuarios_guardar',item:{nombre:'Giselle',usuario:'giselle',password:'contrasegura2',rol:'Encargado',sede:SEDE,email:'giselle@example.com'}});assert.ok(nuevoUsuario.ok);const login=env.post({action:'login',usuario:'giselle',password:'contrasegura2'});assert.ok(login.ok);const r=env.post({token:login.token,action:'caja_corregir',item:{fecha:HOY,sede:SEDE,efectivo_contado:1,caja_fuerte_contada:0,motivo_correccion:'x'}});assert.strictEqual(r.ok,false);})();
console.log('caja-corregir: OK');
